/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Wed Feb 19 10:49:10 2020. */

#include "DC1Config.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DC1ConfigMessage_fields[18] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, DC1ConfigMessage, last_state, last_state, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, power_on_state, last_state, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, power_mode, power_on_state, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, logo_led, power_mode, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, wifi_led, logo_led, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, sub_kinkage, wifi_led, 0),
    PB_FIELD( 20, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, report_interval, sub_kinkage, 0),
    PB_FIELD( 21, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_power_delta, report_interval, 0),
    PB_FIELD( 22, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_power_calibration, energy_power_delta, 0),
    PB_FIELD( 23, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_voltage_calibration, energy_power_calibration, 0),
    PB_FIELD( 24, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_current_calibration, energy_voltage_calibration, 0),
    PB_FIELD( 25, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_kWhtoday, energy_current_calibration, 0),
    PB_FIELD( 26, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_kWhyesterday, energy_kWhtoday, 0),
    PB_FIELD( 27, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_kWhtotal, energy_kWhyesterday, 0),
    PB_FIELD( 28, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_kWhdoy, energy_kWhtotal, 0),
    PB_FIELD( 29, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_kWhtotal_time, energy_kWhdoy, 0),
    PB_FIELD( 30, UINT32  , SINGULAR, STATIC  , OTHER, DC1ConfigMessage, energy_max_power, energy_kWhtotal_time, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
