/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Sat Feb 15 11:23:30 2020. */

#include "GlobalConfig.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t GlobalConfigMessage_fields[9] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, GlobalConfigMessage, wifi, wifi, &WifiConfigMessage_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, GlobalConfigMessage, http, wifi, &HttpConfigMessage_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, GlobalConfigMessage, mqtt, http, &MqttConfigMessage_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, GlobalConfigMessage, debug, mqtt, &DebugConfigMessage_fields),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, GlobalConfigMessage, cfg_version, debug, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, GlobalConfigMessage, module_crc, cfg_version, 0),
    PB_FIELD(  7, BYTES   , SINGULAR, STATIC  , OTHER, GlobalConfigMessage, module_cfg, module_crc, 0),
    PB_FIELD(  8, STRING  , SINGULAR, STATIC  , OTHER, GlobalConfigMessage, uid, module_cfg, 0),
    PB_LAST_FIELD
};

const pb_field_t WifiConfigMessage_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, WifiConfigMessage, ssid, ssid, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, pass, ssid, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, WifiConfigMessage, is_static, pass, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, ip, is_static, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, sn, ip, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, gw, sn, 0),
    PB_FIELD(  7, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, ntp, gw, 0),
    PB_LAST_FIELD
};

const pb_field_t HttpConfigMessage_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, HttpConfigMessage, port, port, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, HttpConfigMessage, user, port, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, HttpConfigMessage, pass, user, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, HttpConfigMessage, ota_url, pass, 0),
    PB_LAST_FIELD
};

const pb_field_t MqttConfigMessage_fields[10] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, MqttConfigMessage, server, server, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, port, server, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, user, port, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, pass, user, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, MqttConfigMessage, retain, pass, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, topic, retain, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, MqttConfigMessage, discovery, topic, 0),
    PB_FIELD(  8, STRING  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, discovery_prefix, discovery, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, interval, discovery_prefix, 0),
    PB_LAST_FIELD
};

const pb_field_t DebugConfigMessage_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, DebugConfigMessage, type, type, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, DebugConfigMessage, server, type, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, DebugConfigMessage, port, server, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(GlobalConfigMessage, wifi) < 65536 && pb_membersize(GlobalConfigMessage, http) < 65536 && pb_membersize(GlobalConfigMessage, mqtt) < 65536 && pb_membersize(GlobalConfigMessage, debug) < 65536 && pb_membersize(GlobalConfigMessage, module_cfg) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_GlobalConfigMessage_WifiConfigMessage_HttpConfigMessage_MqttConfigMessage_DebugConfigMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for GlobalConfigMessage.module_cfg is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
