name: Build Firmware

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO
      run: |
        cd /home/runner/work/esp_dc1/esp_dc1
        platformio run 

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: firmware
        path: /home/runner/work/esp_dc1/esp_dc1/.pio/build/dc1/firmware.bin
